version: '3.3'
services:
  app:
    image: ghcr.io/bbnavi/ocpdb-proxy:main
    networks:
     - public
    logging:
      driver: awslogs
    deploy:
      labels:
        traefik.docker.network: public
        traefik.enable: 'true'
        traefik.http.routers.bbnavi-ocpdb-proxy.entrypoints: https
        traefik.http.routers.bbnavi-ocpdb-proxy.rule: Host(`ocpdb.bbnavi.de`)
        traefik.http.routers.bbnavi-ocpdb-proxy.tls.certresolver: acme
        traefik.http.services.bbnavi-ocpdb-proxy.loadbalancer.server.port: '80'
      restart_policy:
        condition: on-failure
      placement:
        constraints:
         - node.role == worker
networks:
  public:
    external: true