name: Docker Image CI

on:
  push:
    branches: [ epam* ]
  pull_request:
    branches: [ epam* ]

jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: git.bbnavi.de
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: git.bbnavi.de/bbnavi-reg/ocpdb-proxy:latest